spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
jwt:
  secret: ${JWT_SECRET:"mC+gCDTcFDFlbEvVr67QqzGf5Gi+VPVoxPuSj7C1cj4="}
