spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Raha
    username: postgres
    password: postgres
jwt:
  secret: "mC+gCDTcFDFlbEvVr67QqzGf5Gi+VPVoxPuSj7C1cj4="